export const surpriseMePrompts = [
  'a bed in the shape of a sliced lemon',
  'a surrealist dream-like oil painting by Salvador Dalí of a dog playing video games',
  'blue birds shopping for groceries in Sri Lanka',
  'an oil painting by Da Vinci of a humanoid bear praying',
  'Sumerian mad scientist mixing sparkling chemicals, digital art',
  "a macro 55mm photograph of two baby aliens in Maldives, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute arctic mermaid in an aquarium on a dark blue background, digital art',
  'an astronaut squirrel lounging in a tropical resort on Moon, vaporwave',
  'an oil painting portrait of a shiba inu wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a honey and bananas',
  'a pencil and watercolor drawing of a bright city in the future with flying buses',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel orange water, next to a big doors, digital art',
  'a fortune-telling samoyed reading your fate in a giant watermelon, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of a stork in a futuristic war',
  'a painting of a rose in the style of Starry Night',
  'a glass of juice that looks like a monster, knitted out of wool',
  'A plush toy Zeus sitting against a golden wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored UFO flying above a reflective river',
  'A comic book cover of a giraffe wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a cute snake hugging a white frog',
  'A photo of a yellow fur wolf standing in a purple forest',
  "A photo of Michelangelo's sculpture of David coding",
  'A humanoid dragon riding a horse on Venus, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with green eyes and natural red hair',
  'A dog standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Donkey Kong world',
  'A velociraptor working as a bartender, lomography',
  'A man walking through the bustling streets of Rome at night, lit by many soft lights, 50mm lens',
  'A phone that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost The Godfather 1990 Japanese Anime',
  'A fruit salad in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Elephant, Blade Runner Cyberpunk',
  'An cosmonaut encountering an alien plant life form on a distant yellow planet, photography',
  'A baby dinosaur exploring underwater world, photography',
  'A Man falling in Love with AI, digital art',
  'A photograph of a cyborg exploring Belgrade at night, lomography',
  'Dracula walking down the street of London in the 1700s, black and white photography',
  'Synthwave helicopter',
  'A man wanders through the rainy streets of Beijing, with bright lights, 50mm',
  'A star-shaped UFO flying above Moscow, digital art',
];